#!/usr/bin/env python3

from contextlib import contextmanager
import os
import subprocess
import sys
import shutil
from pathlib import Path

PYTHON_VERSIONS = os.getenv('PYTHON_VERSIONS', '3.8 3.9 3.10 3.11 3.12 3.13').split()

exe = ""
prefix = ""


def shell(cmd: str) -> None:
    subprocess.run(cmd, shell=True, check=True)

@contextmanager
def environ(**kwargs):
    original = dict(os.environ)
    os.environ.update(kwargs)
    try:
        yield
    finally:
        os.environ.clear()
        os.environ.update(original)


def uv_install():
    uv_opts = ""
    if "UV_RESOLUTION" in os.environ:
        uv_opts = f"--resolution={os.getenv('UV_RESOLUTION')}"
    cmd = f"uv pip compile {uv_opts} pyproject.toml devdeps.txt | uv pip install -r -"
    shell(cmd)
    if "CI" not in os.environ:
        shell("uv pip install --no-deps -e .")
    else:
        shell("uv pip install --no-deps .")


def setup():
    if not shutil.which("uv"):
        print("make: setup: uv must be installed, see https://github.com/astral-sh/uv", file=sys.stderr)
        return 1

    print("Installing dependencies (default environment)")
    default_venv = Path(".venv")
    if not default_venv.exists():
        shell("uv venv --python python")
    uv_install()

    if PYTHON_VERSIONS:
        for version in PYTHON_VERSIONS:
            print(f"\nInstalling dependencies (python{version})")
            venv_path = Path(f".venvs/{version}")
            if not venv_path.exists():
                shell(f"uv venv --python {version} {venv_path}")
            with environ(VIRTUAL_ENV=str(venv_path.resolve())):
                uv_install()


def activate(path):
    global exe, prefix

    if (bin := Path(path, "bin")).exists():
        activate_script = bin / "activate_this.py"
    elif (scripts := Path(path, "Scripts")).exists():
        activate_script = scripts / "activate_this.py"
        exe = ".exe"
        prefix = f"{path}/Scripts/"
    else:
        raise ValueError(f"make: activate: Cannot find activation script in {path}")

    if not activate_script.exists():
        raise ValueError(f"make: activate: Cannot find activation script in {path}")

    exec(activate_script.read_text(), dict(__file__=str(activate_script)))


def run(version, cmd, *args, **kwargs):
    kwargs = {"check": True, **kwargs}
    if version == "default":
        activate(".venv")
        subprocess.run([f"{prefix}{cmd}{exe}", *args], **kwargs)
    else:
        activate(f".venvs/{version}")
        os.environ["MULTIRUN"] = "1"
        subprocess.run([f"{prefix}{cmd}{exe}", *args], **kwargs)


def multirun(cmd, *args, **kwargs):
    if PYTHON_VERSIONS:
        for version in PYTHON_VERSIONS:
            run(version, cmd, *args, **kwargs)
    else:
        run("default", cmd, *args, **kwargs)


def allrun(cmd, *args, **kwargs):
    run("default", cmd, *args, **kwargs)
    if PYTHON_VERSIONS:
        multirun(cmd, *args, **kwargs)


def clean():
    paths_to_clean = [
        "build", "dist", "htmlcov", "site", ".coverage*", ".pdm-build"
    ]
    for path in paths_to_clean:
        shell(f"rm -rf {path}")
    
    cache_dirs = [
        ".cache", ".pytest_cache", ".mypy_cache", ".ruff_cache", "__pycache__"
    ]
    for path in Path(".").rglob("*"):
        if any(path.match(pattern) for pattern in cache_dirs) and not (path.match(".venv") or path.match(".venvs")):
            shutil.rmtree(path)


def vscode():
    Path(".vscode").mkdir(parents=True, exist_ok=True)
    shell("cp -v config/vscode/* .vscode")


def main():
    args = list(sys.argv[1:])
    if not args or args[0] == "help":
        if len(args) > 1:
            run("default", "duty", "--help", args[1])
        else:
            print("Available commands")
            print("  help                  Print this help. Add task name to print help.")
            print("  setup                 Setup all virtual environments (install dependencies).")
            print("  run                   Run a command in the default virtual environment.")
            print("  multirun              Run a command for all configured Python versions.")
            print("  allrun                Run a command in all virtual environments.")
            print("  3.x                   Run a command in the virtual environment for Python 3.x.")
            print("  clean                 Delete build artifacts and cache files.")
            print("  vscode                Configure VSCode to work on this project.")
            try:
                run("default", "python", "-V", capture_output=True)
            except (subprocess.CalledProcessError, ValueError):
                pass
            else:
                print("\nAvailable tasks")
                run("default", "duty", "--list")
        return 0

    while args:
        cmd = args.pop(0)

        if cmd == "run":
            run("default", *args)
            return 0

        if cmd == "multirun":
            multirun(*args)
            return 0

        if cmd == "allrun":
            allrun(*args)
            return 0

        if cmd.startswith("3."):
            run(cmd, *args)
            return 0

        opts = []
        while args and (args[0].startswith("-") or "=" in args[0]):
            opts.append(args.pop(0))

        if cmd == "clean":
            clean()
        elif cmd == "setup":
            setup()
        elif cmd == "vscode":
            vscode()
        elif cmd == "check":
            multirun("duty", "check-quality", "check-types", "check-docs")
            run("default", "duty", "check-api")
        elif cmd in {"check-quality", "check-docs", "check-types", "test"}:
            multirun("duty", cmd, *opts)
        else:
            run("default", "duty", cmd, *opts)


if __name__ == "__main__":
    sys.exit(main())
